default: &default
  username: postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  host: localhost
  port: 3011
  database: oq_development

test:
  <<: *default
  host: localhost
  port: 3011
  database: oq_test

production:
  <<: *default
  host: pg
  database: oq_production
