version: '3'
services:
  pg:
    image: postgres:12
    volumes:
      - /opt/oq/pg_data:/var/lib/postgresql/data
  web:
    build:
      context: ..
      dockerfile: ./ops/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "80:3000"
    depends_on:
      - pg
    volumes:
      - /opt/oq/bundle:/usr/local/bundle/
