version: '3'
services:

  pg:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: ./ops/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - pg
    volumes:
      - bundle:/usr/local/bundle/
      - assets:/app/public/assets
#      - /opt/oq/log:/app/log

  nginx:
    image: nginx:stable
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - .ops/config/nginx.d:/etc/ngingx/conf.d
      - assets:/var/www/assets

volumes:
  pg_data:
  bundle:
  assets:
