version: '3'
services:

  pg:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: ./ops/app.Dockerfile
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - pg
    expose:
      - 3000
    volumes:
      - bundle:/usr/local/bundle/
      - assets:/app/public/assets
      - /opt/oq/log:/app/log

  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - assets:/var/www/assets:ro
      - /opt/oq/log:/var/log/nginx

volumes:
  pg_data:
  bundle:
  assets:
