version: '3'
services:

  pg:
    image: postgres:12
    volumes:
      - ../../var/pg_data:/var/lib/postgresql/data

  app:
    image: app:build
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - pg
    expose:
      - 3000
    volumes:
      - ../../var/log:/app/log

  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../var/log:/var/log/nginx
      - ../../certbot/conf:/etc/letsencrypt
      - ../../certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ../../certbot/conf:/etc/letsencrypt
      - ../../certbot/www:/var/www/certbot
