version: '3'
services:

  pg:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: ./ops/app.Dockerfile
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - pg
    expose:
      - 3000
    volumes:
      - bundle:/usr/local/bundle/
      - assets:/app/public/assets
      - /opt/oq/log:/app/log

  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - assets:/var/www/assets:ro
      - /opt/oq/log:/var/log/nginx
      - /opt/oq/certbot/conf:/etc/letsencrypt
      - /opt/oq/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /opt/oq/certbot/conf:/etc/letsencrypt
      - /opt/oq/certbot/www:/var/www/certbot

volumes:
  pg_data:
  bundle:
  assets:
