version: '3'
services:

  pg:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - ../../../../var/pg_data:/var/lib/postgresql/data

  app:
    image: app:build
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    restart: unless-stopped
    depends_on:
      - pg
    ports:
      - 3000:3000
    volumes:
      - ../../../../var/log:/app/log

  nginx:
    image: nginx:build
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../../../var/log:/var/log/nginx
      - ../../../../var/letsencrypt:/etc/letsencrypt
